server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: movie-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3333/movie-db
    username: movie-user
    password: movie-password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:movie-service.sql
      continue-on-error: true

info:
  application:
    name: movie-service

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
